export const BACKEND_URL = "https://manolms.com/api"
export const BACKEND_URL_SOCKET = "https://manolms.com"
// export const BACKEND_URL = "http://localhost:4000/api"
// export const BACKEND_URL_SOCKET = "http://localhost:4000"
// export const BACKEND_URL = "https://tca-backend-twbl.onrender.com/api"
export const default_profile = "https://firebasestorage.googleapis.com/v0/b/tca-backend-454ca.appspot.com/o/file-path?alt=media&token=88e392aa-8182-4f24-bbc1-e9f3e58082f0"
// export const BACKEND_URL = "https://tca-backend-twbl.onrender.com/api"
