export const qualification = [
    "BS Mathematics",
    "BS Physics",
    "BS Biology",
    "BS Chemistry",
    "BS Computer Science",
    "BS Electrical Engineering",
    "BS Mechanical Engineering",
    "BS Civil Engineering",
    "BS Industrial Engineering",
    "BS Chemical Engineering",
    "BS Environmental Engineering",
    "BS Materials Science",
    "BS Aerospace Engineering",
    "BS Biomedical Engineering",
    "BS Computer Engineering",
    "BS Electrical Engineering",
    "BS Mechanical Engineering",
    
    "MS Mathematics",
    "MS Physics",
    "MS Biology",
    "MS Chemistry",
    "MS Computer Science",
    "MS Electrical Engineering",
    "MS Mechanical Engineering",
    "MS Civil Engineering",
    "MS Industrial Engineering",
    "MS Chemical Engineering",
    "MS Environmental Engineering",
    "MS Materials Science",
    "MS Aerospace Engineering",
    "MS Biomedical Engineering",
    "MS Computer Engineering",
    "MS Electrical Engineering",
    "MS Mechanical Engineering",
];

export const experience = [
    "1 Year",
    "2 Years",
    "3 Years",
    "4 Years",
    "5 Years",
    "6 Years",
    "7 Years",
    "8 Years",
    "9 Years",
    "10 Years",
];